version: "3.3"

services: 
  gcp-cloud-identity-debug-java:
    image: comworkio/gcp-cloud-identity-debug-java:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: java_runtime
