version: "3.3"

services: 
  gcp-cloud-identity-debug-php:
    image: comworkio/gcp-cloud-identity-debug-php:latest
    env_file:
      - .env
    volumes:
      - ./credentials.json:/credentials.json
    build: 
      context: .
      dockerfile: Dockerfile
